name = "TestRust"
uuid = "2d738727-85e0-4460-b9a4-b1b23cc2a02e"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[deps]
RustCall = "7ac5b1a4-9e37-4f0e-9aa3-3305a66bfb1c"

[sources]
RustCall = {url = "https://github.com/AtelierArith/RustCall.jl", rev = "main"}

[compat]
RustCall = "0.1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Jive"]
